### ISSUE TITLE
photo

### ISSUE THREAD

**Issue by rodzyk** [Predatomm/NewRoz#1]
Знайди рецепт піцци!

**Comment by Predatomm** [comment]
![pizza](https://cloud.githubusercontent.com/assets/9738354/5042591/de7cac8e-6be0-11e4-80af-00a1f13509e4.jpg)

Кулінарні рецепти

14 найсмачніших рецептів піци

Тісто для італійської піци.
Склад:
Вода — 450 мл; 
Сухі дріжджі — 4 чайні ложки; 
Оливкова олія — 4 столові ложки; 
Борошно — 600 грамів; 
Сіль — одна щіпка, можна при бажанні морської солі.
Рецепт:
У зручний для вас посуд, обов’язково підігрий, налити 150 грамів теплої води і покласти дріжджі, ретельно перемішати. Як тільки дріжджі розчиняться, насипати 150 грам борошна, акуратно вимісити і поставити в темне тепле місце (наприклад в заздалегідь, злегка розігріту духовку) на пів години. 
По закінченню 30 хвилин, в тісто додати оливкову олію, сіль 300 мг води, 450 г борошно і якісно замісити тісто. Вимісити тісто для піци поставити на 2 години в темне, тихе місце періодично поглядати і «підмішувати», це робити в тому випадку, якщо тісто почне «тікати».
Даний рецепт тесту розрахований на дві піци.
Тепер тісто для піци готове, пора приступити до основного акорду-начинку.

**Comment by lolka123456** [comment]
![39](https://cloud.githubusercontent.com/assets/9738651/5042615/6263197a-6be1-11e4-9751-5a1a25d82b8c.jpg)

Тісто на піцу (2 шт. Діаметром 30 см.).

Інгредієнти:

2/3 ст. теплої води, 1 ст. л. оливкової олії, 1 ч. л. цукру, 0,5 ч. л. солі, 6,5 г. сухих дріжджів, 2-2,5 ст. борошна.

Спосіб приготування:
1. Воду змішуємо з оливковою олією;
2. Борошно змішуємо з дріжджами, цукром і сіллю у великій мисці;
3. Робимо поглиблення в муці і виливаємо туди воду з оливковою олією;
4. Замішувати не туге тісто;
5. Ставимо тісто на півгодини в тепле місце.

Коли тісто підійде поділяємо на дві частини, розкачуємо і кладемо інгредієнти за смаком.
